package:
  name: molsysmt
  version: 0.1.1

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - pandas
    - MDAnalysis
    - mdtraj
    - openmm
    - openmmtools
    - biopython
    - nglview
    - pdbfixer
    - parmed
    - yank

about:
  home: https://uibcdf.org
  license: MIT License
  summary: ""
  description: |
    This library provides some useful classes, functions, pipes and wrappers daily used in the uibcdf lab when molecular systems are manipulated.
  dev_url: https://github.com/uibcdf/MolSysMT
  doc_url: https://uibcdf.org
