package:
  name: moldynsak
  version: 0.2

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy
    - mdtraj
    - molsyssak

about:
  home: https://uibcdf.org
  license: MIT License
  summary: ""
  description: |
    This library provides some useful classes, functions, pipes and wrappers daily used in the uibcdf lab when Molecular Dynamics trajectories, or just molecular systems with coordinates, are manipulated.
  dev_url: https://github.com/uibcdf/MolDynSAK
  doc_url: https://uibcdf.org/MolDynSAK
